sphana:
  rag:
    # database:
    #   root_dir: "./.database"
    #   index_details_dir: "./index_details"
    #   shard_details_dir: "./shard_details"
    #   index_vectors_dir: "./index_vectors"
    #   document_details_dir: "./document_details"
    #   parent_chunk_details_dir: "./parent_chunk_details"
    #   child_chunk_details_dir: "./child_chunk_details"
    self_node: "http://localhost2:5001"
    nodes:
      - "http://localhost:5001"
