sphana:
  rag:
    # database:
    #   root_dir: "./.database"
    #   index_details_dir: "./index_details"
    #   shard_details_dir: "./shard_details"
    #   index_vectors_dir: "./index_vectors"
    #   document_details_dir: "./document_details"
    #   parent_chunk_details_dir: "./parent_chunk_details"
    #   child_chunk_details_dir: "./child_chunk_details"

    cluster:
      self_address: "127.0.0.2:9100"
      nodes_file: "./services/sphana-rag-service/src/resources/configs/nodes.txt"
      backup_count: 1
      wal_dir: null